name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup up Ruby 2.5.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.5
      - name: Build and test with Rake
        run: |
          gem install bundler -v 1.17.3
          bundle install
          bundle exec rake